const servicePages = {
  intermodal:{title:'Intermodal Transportation',tagline:'Smarter freight movement across road, rail, and ocean networks.',image:'transport.jpg',desc:'Skylink Corridors combines road, rail, and ocean transportation to move freight efficiently across regional and international supply chains. Coordinated planning reduces handling, controls cost, and maintains end-to-end shipment visibility.',focus:['Multi-Modal Coordination','Real-Time Tracking','Dedicated Operations Team','Flexible Capacity'],tags:['Automotive','Consumer Goods','E-Commerce','Retail','Chemical']},
  'asset-based':{title:'Asset-Based Domestic Transportation',tagline:'Reliable domestic capacity backed by our dedicated fleet.',image:'transport.jpg',desc:'Our asset-based domestic transportation service gives shippers dependable fleet capacity, professional drivers, and direct operational control across Pakistan. Every movement is planned for safety, consistency, and on-time performance.',focus:['Owned Fleet Capacity','Nationwide Coverage','Driver & Safety Management','Shipment Visibility'],tags:['Retail','Automotive','Consumer Goods','Building Materials']},
  'marine-container':{title:'Marine Container Solutions (MCS)',tagline:'End-to-end container movement between ports and inland destinations.',image:'forwarding.jpg',desc:'We coordinate marine containers from port availability through inland delivery, including drayage, documentation, empty returns, and exception management. Our teams keep containers moving while reducing detention and demurrage exposure.',focus:['Port Coordination','Container Drayage','Documentation Support','Detention Control'],tags:['Importers','Exporters','Retail','Manufacturing']},
  'cross-border':{title:'Cross-Border Logistics',tagline:'Secure freight movement across Pakistan, Afghanistan, and Central Asia.',image:'cross-border.jpg',desc:'Skylink Corridors manages cross-border transportation with route planning, customs coordination, documentation, and milestone visibility. Regional expertise helps customers navigate complex corridors with confidence and operational continuity.',focus:['Customs Coordination','Regional Route Expertise','Secure Transloading','Cross-Border Visibility'],tags:['Retail','Industrial','Humanitarian','Consumer Goods']},
  'temperature-controlled':{title:'Temperature-Controlled Transportation',tagline:'Cold chain integrity from origin to destination.',image:'transport.jpg',desc:'Our temperature-controlled transportation protects sensitive products with suitable equipment, monitored conditions, trained handling, and rapid exception response. Every shipment is managed to preserve quality and cold-chain integrity.',focus:['Temperature Monitoring','Reefer Capacity','Cold-Chain Compliance','Exception Management'],tags:['Healthcare','Food & Beverage','Chemical','Retail']},
  'truck-brokerage':{title:'Truck Brokerage',tagline:'Flexible capacity from a dependable carrier network.',image:'transport.jpg',desc:'Our truck brokerage team connects customer demand with qualified carriers across diverse equipment types and lanes. Centralized coordination, carrier vetting, and proactive tracking deliver scalable capacity without compromising control.',focus:['Qualified Carrier Network','Flexible Equipment','Rate & Route Optimization','Proactive Tracking'],tags:['Retail','Manufacturing','Automotive','Consumer Goods']},
  'asset-trucking':{title:'Asset Trucking',tagline:'Dedicated equipment and operational control for critical freight.',image:'transport.jpg',desc:'Skylink asset trucking provides reliable trucks, trained drivers, and disciplined dispatch management for time-sensitive freight. Direct fleet control supports predictable service, safety, and responsive capacity planning.',focus:['Dedicated Assets','Professional Drivers','Dispatch Control','Preventive Maintenance'],tags:['Automotive','Industrial','Retail','Building Materials']},
  'dedicated-trucking':{title:'Dedicated Trucking',tagline:'Fleet capacity designed around your network.',image:'transport.jpg',desc:'Dedicated trucking assigns vehicles, drivers, and operating processes to your business. We design routes and schedules around recurring demand to improve utilization, consistency, and customer service.',focus:['Dedicated Fleet','Custom Route Design','Consistent Scheduling','Performance Reporting'],tags:['Retail','Automotive','Consumer Goods','Manufacturing']},
  ftl:{title:'Full Truckload (FTL)',tagline:'Direct, secure transportation for full-load shipments.',image:'transport.jpg',desc:'Our full truckload service moves high-volume freight directly from pickup to delivery with fewer handling points. Dedicated equipment, route planning, and active monitoring support fast and reliable transit.',focus:['Direct Point-to-Point Service','Multiple Equipment Types','Expedited Options','End-to-End Tracking'],tags:['Retail','Industrial','Automotive','Consumer Goods']},
  ltl:{title:'LTL Freight Optimization',tagline:'Cost-effective transportation for smaller freight volumes.',image:'warehouse.jpg',desc:'LTL freight optimization consolidates compatible shipments, selects efficient routes, and manages each handoff carefully. Customers gain economical capacity while maintaining delivery visibility and service standards.',focus:['Shipment Consolidation','Route Optimization','Freight Classification','Milestone Tracking'],tags:['E-Commerce','Retail','Consumer Goods','Healthcare']},
  'cross-dock':{title:'Cross Dock Operations',tagline:'Faster flow-through with minimal storage and handling.',image:'warehouse.jpg',desc:'Our cross-dock operations transfer inbound freight quickly into outbound routes, reducing storage time and inventory dwell. Structured receiving, sorting, staging, and dispatch processes keep products moving efficiently.',focus:['Rapid Transfer','Load Consolidation','Sort & Segregation','Scheduled Dispatch'],tags:['Retail','E-Commerce','Food & Beverage','Consumer Goods']},
  'retail-consolidation':{title:'Retail Consolidation',tagline:'Coordinated inbound freight for reliable store replenishment.',image:'warehouse.jpg',desc:'Retail consolidation combines supplier shipments into planned, store-ready loads. We manage receiving, scheduling, labeling, and outbound delivery to reduce cost and improve compliance with retailer requirements.',focus:['Vendor Consolidation','Appointment Scheduling','Retail Compliance','Store-Ready Delivery'],tags:['Retail','Consumer Goods','Food & Beverage','E-Commerce']},
  ecommerce:{title:'E-Commerce Fulfillment',tagline:'Fast, accurate fulfillment built around the customer experience.',image:'ecommerce.jpg',desc:'Our e-commerce fulfillment solution manages inventory, orders, picking, packing, dispatch, and returns. Flexible workflows support growing online brands with accurate execution and dependable final-mile handoffs.',focus:['Inventory Management','Pick & Pack','Order Integration','Returns Processing'],tags:['E-Commerce','Retail','Consumer Goods','Healthcare']},
  'international-freight':{title:'International Freight',tagline:'Connected air and ocean freight across global trade lanes.',image:'forwarding.jpg',desc:'Skylink Corridors coordinates international air and ocean freight with carrier booking, documentation, customs support, and destination delivery. A single operations team maintains visibility across every milestone.',focus:['Air & Ocean Freight','Carrier Booking','Trade Documentation','Destination Coordination'],tags:['Importers','Exporters','Retail','Industrial']},
  drayage:{title:'International Drayage',tagline:'Reliable port-to-door container transportation.',image:'forwarding.jpg',desc:'International drayage connects ports, terminals, warehouses, and final destinations through coordinated container trucking. We manage appointments, equipment, documentation, and empty returns to protect schedules.',focus:['Port & Terminal Moves','Appointment Management','Container Tracking','Empty Return Control'],tags:['Importers','Exporters','Retail','Manufacturing']},
  'reverse-logistics':{title:'Reverse Logistics',tagline:'Efficient returns, recovery, and product disposition.',image:'warehouse.jpg',desc:'Our reverse logistics programs collect returned goods, inspect and sort inventory, coordinate recovery, and route products to the right disposition. Clear workflows improve customer experience and recover value.',focus:['Returns Collection','Inspection & Sorting','Inventory Recovery','Disposition Management'],tags:['E-Commerce','Retail','Consumer Goods','Healthcare']},
  'middle-final-mile':{title:'Middle Mile & Final Mile Delivery',tagline:'Connected movement from fulfillment center to final destination.',image:'transport.jpg',desc:'We coordinate middle-mile transfers and final-mile delivery as one connected operation. Route planning, controlled handoffs, delivery visibility, and exception management support consistent service at scale.',focus:['Hub-to-Hub Transport','Route Optimization','Proof of Delivery','Exception Resolution'],tags:['E-Commerce','Retail','Consumer Goods','Healthcare']},
  'home-business-delivery':{title:'Home & Business Delivery',tagline:'Professional delivery experiences for every recipient.',image:'transport.jpg',desc:'Home and business delivery services provide scheduled, trackable delivery to residential and commercial locations. Customer communication, proof of delivery, and trained teams support a dependable experience.',focus:['Scheduled Delivery','Customer Notifications','Proof of Delivery','Commercial Stops'],tags:['E-Commerce','Retail','Consumer Goods','Healthcare']},
  'big-bulky':{title:'Big & Bulky Last Mile Delivery',tagline:'Specialized final-mile care for oversized products.',image:'transport.jpg',desc:'Our big and bulky delivery service handles oversized, heavy, and high-value products with specialized equipment and trained crews. Appointment scheduling and careful handling protect the product and customer experience.',focus:['Specialized Equipment','Appointment Delivery','Two-Person Handling','Delivery Confirmation'],tags:['Furniture','Appliances','Building Materials','Retail']}
};

const industryPages = {
  retail:{title:'Retail Logistics',tagline:'Responsive logistics for stores, suppliers, and customers.',image:'warehouse.jpg',desc:'Skylink Corridors helps retailers coordinate supplier inbound freight, inventory flow, store replenishment, and customer delivery. Our flexible transport and warehousing network responds quickly to promotions, seasonal peaks, and changing demand.',focus:['Vendor Consolidation','Store Replenishment','Peak-Season Capacity','Delivery Visibility'],tags:['Transportation','Warehousing','Cross Dock','Final Mile']},
  'private-equity':{title:'Private Equity Logistics',tagline:'Scalable supply chain support across portfolio companies.',image:'about.jpg',desc:'We help private equity teams stabilize, integrate, and improve logistics operations across portfolio businesses. Standardized reporting and flexible capacity create visibility while supporting growth, acquisitions, and operational transformation.',focus:['Network Assessment','Portfolio Standardization','Cost Optimization','Scalable Capacity'],tags:['Transportation','Warehousing','Technology','Reporting']},
  ecommerce:{title:'E-Commerce Logistics',tagline:'Fulfillment and delivery designed for online growth.',image:'ecommerce.jpg',desc:'Our e-commerce logistics platform connects inventory, order fulfillment, transportation, final-mile delivery, and returns. Scalable processes help brands deliver accurately and quickly while protecting the customer experience.',focus:['Order Fulfillment','Inventory Accuracy','Final-Mile Delivery','Returns Management'],tags:['Warehousing','Fulfillment','Transportation','Reverse Logistics']},
  healthcare:{title:'Healthcare Logistics',tagline:'Controlled, visible handling for critical healthcare products.',image:'transport.jpg',desc:'Healthcare logistics requires disciplined handling, reliable timing, and clear chain-of-custody visibility. We coordinate suitable transport and storage processes for medical products, equipment, and healthcare supplies.',focus:['Chain of Custody','Temperature Control','Priority Handling','Delivery Visibility'],tags:['Cold Chain','Dedicated Transport','Warehousing','Final Mile']},
  cpg:{title:'CPG Logistics',tagline:'High-velocity logistics for consumer packaged goods.',image:'warehouse.jpg',desc:'We support consumer packaged goods manufacturers with inbound materials, warehousing, retail consolidation, and responsive distribution. Structured planning keeps fast-moving inventory available across changing demand cycles.',focus:['Retail Compliance','Inventory Flow','Promotional Capacity','Multi-Channel Distribution'],tags:['Warehousing','Retail Consolidation','FTL & LTL','Cross Dock']},
  'food-beverage':{title:'Food & Beverage Logistics',tagline:'Fresh, compliant movement across the food supply chain.',image:'transport.jpg',desc:'Our food and beverage logistics services coordinate time-sensitive transport, suitable storage, route planning, and delivery scheduling. Operational controls help protect product condition, freshness, and service reliability.',focus:['Cold-Chain Support','Time-Critical Delivery','Lot Visibility','Seasonal Capacity'],tags:['Temperature Controlled','Warehousing','FTL','Retail Delivery']},
  'durable-goods':{title:'Durable Goods Logistics',tagline:'Reliable handling for high-value, long-life products.',image:'warehouse.jpg',desc:'Durable goods require careful handling, inventory control, and dependable transportation. We coordinate inbound materials, storage, distribution, and specialized final-mile delivery for products of varied size and value.',focus:['Damage Prevention','Inventory Control','Special Handling','Scheduled Delivery'],tags:['Warehousing','FTL','Big & Bulky','Final Mile']},
  building:{title:'Building Products & Materials Logistics',tagline:'Job-site ready transportation for construction supply chains.',image:'transport.jpg',desc:'We move building products and materials with equipment selection, load planning, delivery scheduling, and site coordination. Reliable capacity and proactive communication help contractors and suppliers maintain project timelines.',focus:['Equipment Selection','Job-Site Scheduling','Heavy-Load Planning','Proof of Delivery'],tags:['Flatbed Transport','Dedicated Trucking','Warehousing','Final Mile']},
  automotive:{title:'Automotive Logistics',tagline:'Synchronized transportation for automotive supply chains.',image:'transport.jpg',desc:'Automotive logistics demands precise scheduling and continuous visibility. We coordinate inbound components, production-support freight, aftermarket distribution, and expedited recovery to keep operations moving.',focus:['Production Scheduling','Parts Consolidation','Expedited Recovery','Shipment Visibility'],tags:['Dedicated Trucking','Cross Dock','FTL & LTL','Cross-Border']},
  glass:{title:'Glass Logistics',tagline:'Specialized care for fragile and high-risk freight.',image:'transport.jpg',desc:'Our glass logistics solutions emphasize equipment suitability, secure loading, careful handling, and controlled delivery. Experienced coordination reduces damage risk from origin through job site or customer destination.',focus:['Secure Load Planning','Specialized Handling','Damage Prevention','Site Coordination'],tags:['Dedicated Transport','Special Equipment','Warehousing','Final Mile']},
  paper:{title:'Paper Logistics',tagline:'Protected, efficient movement for paper and packaging products.',image:'warehouse.jpg',desc:'Paper products need protection from moisture, contamination, and handling damage. We coordinate clean equipment, suitable storage, load planning, and reliable distribution for mills, converters, and customers.',focus:['Moisture Protection','Clean Equipment','Inventory Rotation','Reliable Distribution'],tags:['Warehousing','FTL','Dedicated Trucking','Cross Dock']},
  'wine-spirits':{title:'Wine, Spirits and Breweries Logistics',tagline:'Controlled logistics for beverage production and distribution.',image:'transport.jpg',desc:'We coordinate transport and storage for beverage ingredients, packaging, finished products, and retail orders. Careful handling, temperature awareness, and shipment visibility support product quality and dependable distribution.',focus:['Product Protection','Temperature Awareness','Retail Distribution','Inventory Visibility'],tags:['Temperature Controlled','Warehousing','Retail Delivery','FTL']},
  '3pl':{title:'Asset Solutions for 3PLs',tagline:'Dependable fleet capacity that strengthens your customer promise.',image:'transport.jpg',desc:'Skylink provides 3PL partners with asset-backed capacity, regional execution, and responsive operational support. Our services extend your network while maintaining shipment visibility and consistent service standards.',focus:['Asset-Backed Capacity','White-Label Execution','Regional Coverage','Performance Reporting'],tags:['Dedicated Trucking','FTL & LTL','Cross-Border','Final Mile']},
  chemical:{title:'Chemical Logistics',tagline:'Safety-led transportation for sensitive chemical supply chains.',image:'transport.jpg',desc:'Chemical logistics requires disciplined planning, suitable equipment, documentation, and trained execution. We coordinate each movement with safety, compliance, and product integrity at the center of the operation.',focus:['Safety Procedures','Suitable Equipment','Documentation Control','Shipment Visibility'],tags:['Dedicated Transport','Temperature Control','Warehousing','Cross-Border']}
};

const nav = `<header class="site-header detail-header"><nav class="navbar container" aria-label="Main navigation"><a class="brand" href="/"><img src="/assets/Skylink%20Corridor%20logo%20New.png" alt="Skylink Corridors"></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false"><span></span><span></span><span></span></button><div class="nav-wrap"><div class="nav-item has-menu"><button class="nav-trigger" aria-expanded="false">About Us <span>⌄</span></button><div class="dropdown about-menu"><a href="/about/story">Our Story</a><a href="/about/leadership">Leadership</a><a href="/about/values">Our Values</a><a href="/about/technology">Technology &amp; Innovation</a><a href="/about/sustainability">Sustainability</a><a href="/about/news">News</a><a href="/about/portfolio">Portfolio</a></div></div><div class="nav-item has-menu"><button class="nav-trigger" aria-expanded="false">Services <span>⌄</span></button><div class="dropdown services-menu">${Object.entries(servicePages).map(([slug,p])=>`<a href="/services/${slug}/">${p.title}</a>`).join('')}</div></div><div class="nav-item has-menu"><button class="nav-trigger" aria-expanded="false">Industries <span>⌄</span></button><div class="dropdown industries-menu">${Object.entries(industryPages).map(([slug,p])=>`<a href="/industries/${slug}/">${p.title}</a>`).join('')}</div></div><a class="nav-link" href="/careers/">Careers</a><a class="nav-link" href="/contact/">Contact</a></div><a class="btn quote-btn" href="/contact/">Request a Quote</a></nav></header>`;

const footer = `<footer><div class="container footer-grid"><div class="footer-brand"><img src="/assets/Skylink%20Corridor%20logo%20New.png" alt="Skylink Corridors"><p>Your trusted partner for integrated logistics, transportation, warehousing, freight forwarding, and supply chain solutions across Pakistan, Afghanistan & Central Asia.</p><p>📍 Karachi, Pakistan<br>☎ +92 21 000 0000<br>✉ info@skylinkcorridors.com</p><div class="social-links"><a href="#" aria-label="Facebook">f</a><a href="#" aria-label="Instagram">◎</a><a href="#" aria-label="LinkedIn">in</a></div></div><div><h3>Services</h3><a href="/services/intermodal/">Intermodal Transportation</a><a href="/services/cross-border/">Cross-Border Logistics</a><a href="/services/ftl/">Full Truckload (FTL)</a><a href="/services/ltl/">LTL Freight</a><a href="/services/ecommerce/">E-Commerce Fulfillment</a><a href="/services/international-freight/">International Freight</a></div><div><h3>Industries</h3><a href="/industries/ecommerce/">E-Commerce Logistics</a><a href="/industries/automotive/">Automotive Logistics</a><a href="/industries/healthcare/">Healthcare Logistics</a><a href="/industries/food-beverage/">Food & Beverage</a><a href="/industries/chemical/">Chemical Logistics</a><a href="/industries/cpg/">Consumer Packaged Goods</a></div><div><h3>Company</h3><a href="/about/story">About Us</a><a href="/about/leadership">Leadership</a><a href="/about/sustainability">Sustainability</a><a href="/about/technology">Technology & Innovation</a><a href="/careers/">Careers</a><a href="/contact/">Contact Us</a></div></div><div class="footer-bottom container"><span>© 2026 Skylink Corridors. All rights reserved.</span><span><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a></span></div></footer>`;

const type = document.body.dataset.type;
const slug = document.body.dataset.slug;
const page = (type === 'service' ? servicePages : industryPages)[slug];
if (!page) {
  document.body.innerHTML = '<main class="missing-page"><h1>Page not found</h1><a href="/">Return home</a></main>';
} else {
  const label = type === 'service' ? 'Our Services' : 'Industries We Serve';
  const overviewTitle = type === 'service' ? 'Service Overview' : 'Industry Overview';
  const sectionTitle = type === 'service' ? 'Industries We Serve with This Solution' : 'Solutions for This Industry';
  const descriptions = ['Coordinated planning and execution built around your requirements.','Clear milestones and proactive communication throughout every movement.','Experienced logistics professionals managing day-to-day operations.','Flexible capacity that scales with changing business demand.'];
  document.title = `${page.title} | Skylink Corridors`;
  document.querySelector('meta[name="description"]').content = page.desc;
  document.body.innerHTML = `${nav}<main><section class="detail-hero"><img src="/assets/${page.image}" alt="${page.title}"><div class="detail-hero-overlay"></div><div class="container detail-hero-content"><div class="eyebrow">${label}</div><h1>${page.title}</h1><p>${page.tagline}</p><a class="btn btn-primary" href="/contact/">Request a Quote <span>→</span></a></div></section><section class="detail-overview"><div class="container detail-grid"><div><h2>${overviewTitle}</h2><p class="detail-intro">${page.desc}</p><h3>Key Benefits</h3><ul class="benefit-list"><li>Reliable execution designed around operational priorities</li><li>Reduced delays and avoidable supply chain cost</li><li>Clear visibility from planning through delivery</li><li>Flexible capacity for changing business demand</li><li>Dedicated support and proactive exception management</li></ul></div><div><h3>What We Offer</h3><div class="offer-list">${page.focus.map((item,i)=>`<article><b>•</b><div><h4>${item}</h4><p>${descriptions[i]}</p></div></article>`).join('')}</div></div></div></section><section class="detail-related"><div class="container"><h2>${sectionTitle}</h2><div class="detail-tags">${page.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></div></section><section class="cta detail-cta"><div class="container"><h2>Ready to Strengthen Your Supply Chain?</h2><p>Talk to our logistics team about a solution designed for your operation.</p><a class="btn btn-white" href="/contact/">Contact Our Logistics Experts</a></div></section></main>${footer}`;
}
